version: '3.4'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    user: "0"
    links:
      - influxdb
    volumes:
      # Data persistency
      - ./docker_data/grafana/data:/var/lib/grafana
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      # Data persistency
      - ./docker_data/influxdb/data:/var/lib/influxdb
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6


networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16